on: workflow_dispatch


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx nx run resume:build

      - name: Deploy to Azure
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch --account-name jjohnsonpersonal --destination '$web' --source dist/apps/resume --overwrite true
