on: workflow_dispatch


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx nx run resume:build

      
      - uses: actions/checkout@v4
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: dist/apps/resume
          container_name: $web
          connection_string: ${{ secrets.CONNECTIONSTRING }}
          overwrite: 'true'
